DROP TABLE IF EXISTS BILLING;

CREATE TABLE BILLING (
    ID INT AUTO_INCREMENT,
    TRANSACTION_REFERENCE VARCHAR(250),
    CLIENT_SWIFT_ADDRESS VARCHAR(250),
    MESSAGE_SATUS VARCHAR(250),
    CURRENCY VARCHAR(250),
    AMOUNT VARCHAR(250),
    DATE_TIME_CREATED VARCHAR(250),
    PRIMARY KEY (ID)

);

NSERT INTO BILLING(TRANSACTION_REFERENCE, CLIENT_SWIFT_ADDRESS, MESSAGE_SATUS, CURRENCY, AMOUNT, DATE_TIME_CREATED)
    VALUES ('TX REF', 'SWFTADD', 'COMP', 'ZAR', 100, '2000-10-10 12:12:12');
INSERT INTO BILLING(TRANSACTION_REFERENCE, CLIENT_SWIFT_ADDRESS, MESSAGE_SATUS, CURRENCY, AMOUNT, DATE_TIME_CREATED)
    VALUES ('TX REF', 'SWFT ADD', 'COMP', 'ZAR', 100, '2000-10-10 12:12:12');
INSERT INTO BILLING(TRANSACTION_REFERENCE, CLIENT_SWIFT_ADDRESS, MESSAGE_SATUS, CURRENCY, AMOUNT, DATE_TIME_CREATED)
    VALUES ('TX REF', 'SWFT ADD', 'COMP', 'ZAR', 100, '2000-10-10 12:12:12');